----------------------------------------------------------------------
-- SmartGear -- Pre-Built Target Builds Database
-- AUTO-GENERATED by SmartGear Updater on 2026-04-01 21:41
-- Total builds: 25
-- Do not edit manually -- re-run updater to refresh.
----------------------------------------------------------------------
SmartGear = SmartGear or {}
SmartGear.PreBuilds = {}

SmartGear.PreBuilds["magdd_group_magicka_damage_dealer_arcane"] = {
    name = "Magicka Damage Dealer [Arcane]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Crushing Wall" },
        [EQUIP_SLOT_CHEST] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_HAND] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_HEAD] = { set = "Slimecraw" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_RING2] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_WAIST] = { set = "Tide-Born Wildstalker" },
    },
}

SmartGear.PreBuilds["healer_group_magicka_healer_runemender"] = {
    name = "Magicka Healer [Runemender]",
    role = "Healer",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Perf. Transformative Hope" },
        [EQUIP_SLOT_FEET] = { set = "Syrabanic Marine Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perf. Transformative Hope" },
        [EQUIP_SLOT_HEAD] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_LEGS] = { set = "Syrabanic Marine Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Grand Rejuvenation" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_WAIST] = { set = "Perf. Transformative Hope" },
    },
}

SmartGear.PreBuilds["stamdd_group_stamina_damage_dealer_lost_tomes"] = {
    name = "Stamina Damage Dealer [Lost Tomes]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Merciless Charge" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Ansuul’s Torment" },
        [EQUIP_SLOT_FEET] = { set = "Fargrave Guardian Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Ansuul’s Torment" },
        [EQUIP_SLOT_HEAD] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_LEGS] = { set = "Fargrave Guardian Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_RING2] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Ansuul’s Torment" },
    },
}

SmartGear.PreBuilds["stamdd_group_bow_bow_damage_dealer_arc"] = {
    name = "Bow/Bow Damage Dealer [Arc]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Thunderous Volley" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms Of Relequen" },
    },
}

SmartGear.PreBuilds["stamdd_group_2h_dw_damage_dealer_wreck"] = {
    name = "2H/DW Damage Dealer [Wreck]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Spectral Cloak" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["tank_group_health_tank_sanctum"] = {
    name = "Health Tank [Sanctum]",
    role = "Tank",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Pearlescent Ward" },
        [EQUIP_SLOT_CHEST] = { set = "Turning Tide" },
        [EQUIP_SLOT_FEET] = { set = "Syrabanic Marine Motif" },
        [EQUIP_SLOT_HAND] = { set = "Turning Tide" },
        [EQUIP_SLOT_HEAD] = { set = "Nazaray" },
        [EQUIP_SLOT_LEGS] = { set = "Syrabanic Marine Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Pearlescent Ward" },
        [EQUIP_SLOT_NECK] = { set = "Perfected Pearlescent Ward" },
        [EQUIP_SLOT_OFF_HAND] = { set = "Syrabanic Marine Motif and Lyris Titanborn’s Shield" },
        [EQUIP_SLOT_RING1] = { set = "Perfected Pearlescent Ward" },
        [EQUIP_SLOT_RING2] = { set = "Perfected Pearlescent Ward" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Nazaray" },
        [EQUIP_SLOT_WAIST] = { set = "Turning Tide" },
    },
}

SmartGear.PreBuilds["magdd_group_werewolf_build_claws"] = {
    name = "Werewolf Build [Claws]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Merciless Charge" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Kjalnar’s Nightmare" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Kjalnar’s Nightmare" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["magdd_group_magicka_damage_dealer_curse"] = {
    name = "Magicka Damage Dealer [Curse]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Crushing Wall" },
        [EQUIP_SLOT_CHEST] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_HEAD] = { set = "Slimecraw" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_RING2] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_WAIST] = { set = "Pillar of Nirn" },
    },
}

SmartGear.PreBuilds["healer_group_magicka_healer_scourge"] = {
    name = "Magicka Healer [Scourge]",
    role = "Healer",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_FEET] = { set = "Apostle Motif" },
        [EQUIP_SLOT_HAND] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_HEAD] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_LEGS] = { set = "Apostle Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Grand Rejuvenation" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_WAIST] = { set = "Spell Power Cure" },
    },
}

SmartGear.PreBuilds["stamdd_group_stamina_damage_dealer_reaper"] = {
    name = "Stamina Damage Dealer [Reaper]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Merciless Charge" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_FEET] = { set = "Annihilarch’s Chosen Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_LEGS] = { set = "Annihilarch’s Chosen Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["stamdd_group_bow_bow_damage_dealer_blight"] = {
    name = "Bow/Bow Damage Dealer [Blight]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Thunderous Volley" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms Of Relequen" },
    },
}

SmartGear.PreBuilds["stamdd_group_2h_dw_damage_dealer_cleave"] = {
    name = "2H/DW Damage Dealer [Cleave]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Spectral Cloak" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["tank_group_health_tank_colossus"] = {
    name = "Health Tank [Colossus]",
    role = "Tank",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Crimson Oath’s Rive" },
        [EQUIP_SLOT_CHEST] = { set = "Perf. Saxhleel Champion" },
        [EQUIP_SLOT_FEET] = { set = "Annihilarch’s Chosen Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perf. Saxhleel Champion" },
        [EQUIP_SLOT_HEAD] = { set = "Archdruid Devyric" },
        [EQUIP_SLOT_LEGS] = { set = "Annihilarch’s Chosen Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perf. Puncturing Remedy" },
        [EQUIP_SLOT_NECK] = { set = "Crimson Oath’s Rive" },
        [EQUIP_SLOT_OFF_HAND] = { set = "Annihilarch’s Chosen Motif" },
        [EQUIP_SLOT_RING1] = { set = "Crimson Oath’s Rive" },
        [EQUIP_SLOT_RING2] = { set = "Crimson Oath’s Rive" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Archdruid Devyric" },
        [EQUIP_SLOT_WAIST] = { set = "Perf. Saxhleel Champion" },
    },
}

SmartGear.PreBuilds["magdd_group_magicka_damage_dealer_valakas"] = {
    name = "Magicka Damage Dealer [Valakas]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Crushing Wall" },
        [EQUIP_SLOT_CHEST] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_FEET] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_HAND] = { set = "Tide-Born Wildstalker" },
        [EQUIP_SLOT_HEAD] = { set = "Slimecraw" },
        [EQUIP_SLOT_LEGS] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perf. Null Arca" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Perf. Null Arca" },
        [EQUIP_SLOT_RING2] = { set = "Perf. Null Arca" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Perf. Null Arca" },
        [EQUIP_SLOT_WAIST] = { set = "Tide-Born Wildstalker" },
    },
}

SmartGear.PreBuilds["healer_group_magicka_healer_obsidian"] = {
    name = "Magicka Healer [Obsidian]",
    role = "Healer",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_FEET] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_HAND] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_HEAD] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_LEGS] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Grand Rejuvenation" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_OFF_HAND] = { set = "Slot 5: Cauterize" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_WAIST] = { set = "Spell Power Cure" },
    },
}

SmartGear.PreBuilds["stamdd_group_stamina_damage_dealer_venom"] = {
    name = "Stamina Damage Dealer [Venom]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Merciless Charge" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Null Arca" },
        [EQUIP_SLOT_FEET] = { set = "Moongrave Fane Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Null Arca" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_LEGS] = { set = "Moongrave Fane Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Null Arca" },
    },
}

SmartGear.PreBuilds["stamdd_group_2h_dw_damage_dealer_serpent"] = {
    name = "2H/DW Damage Dealer [Serpent]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Spectral Cloak" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["stamdd_group_bow_bow_damage_dealer_toxin"] = {
    name = "Bow/Bow Damage Dealer [Toxin]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Thunderous Volley" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms Of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms Of Relequen" },
    },
}

SmartGear.PreBuilds["tank_group_health_tank_catalyst"] = {
    name = "Health Tank [Catalyst]",
    role = "Tank",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Turning Tide" },
        [EQUIP_SLOT_FEET] = { set = "Scalecaller Motif" },
        [EQUIP_SLOT_HAND] = { set = "Turning Tide" },
        [EQUIP_SLOT_HEAD] = { set = "Tremorscale" },
        [EQUIP_SLOT_LEGS] = { set = "Scalecaller Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Druid’s Braid" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_OFF_HAND] = { set = "Slot 4: Chains of Dominance" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Tremorscale" },
        [EQUIP_SLOT_WAIST] = { set = "Turning Tide" },
    },
}

SmartGear.PreBuilds["magdd_group_magicka_damage_dealer_mystic"] = {
    name = "Magicka Damage Dealer [Mystic]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Crushing Wall" },
        [EQUIP_SLOT_CHEST] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_FEET] = { set = "Sapiarch Motif" },
        [EQUIP_SLOT_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_HEAD] = { set = "Slimecraw" },
        [EQUIP_SLOT_LEGS] = { set = "Dremora Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_RING2] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Perfected Whorl of Depths" },
        [EQUIP_SLOT_WAIST] = { set = "Pillar of Nirn" },
    },
}

SmartGear.PreBuilds["healer_group_magicka_healer_surge"] = {
    name = "Magicka Healer [Surge]",
    role = "Healer",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_FEET] = { set = "Celestial Motif" },
        [EQUIP_SLOT_HAND] = { set = "Spell Power Cure" },
        [EQUIP_SLOT_HEAD] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_LEGS] = { set = "Celestial Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Perfected Grand Rejuvenation" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Symphony of Blades" },
        [EQUIP_SLOT_WAIST] = { set = "Spell Power Cure" },
    },
}

SmartGear.PreBuilds["stamdd_group_stamina_damage_dealer_windwalker"] = {
    name = "Stamina Damage Dealer [Windwalker]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Merciless Charge" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_FEET] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_LEGS] = { set = "Welkynar Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["stamdd_group_2h_dw_damage_dealer_deathstroke"] = {
    name = "2H/DW Damage Dealer [Deathstroke]",
    role = "StamDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Spectral Cloak" },
        [EQUIP_SLOT_CHEST] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HAND] = { set = "Perfected Arms of Relequen" },
        [EQUIP_SLOT_HEAD] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_NECK] = { set = "Velothi Ur-Mage’s Amulet" },
        [EQUIP_SLOT_RING1] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_RING2] = { set = "Pillar of Nirn" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw" },
        [EQUIP_SLOT_WAIST] = { set = "Perfected Arms of Relequen" },
    },
}

SmartGear.PreBuilds["tank_group_health_tank_capacitor"] = {
    name = "Health Tank [Capacitor]",
    role = "Tank",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Powerful Assault" },
        [EQUIP_SLOT_CHEST] = { set = "Turning Tide" },
        [EQUIP_SLOT_FEET] = { set = "Xivkyn Motif" },
        [EQUIP_SLOT_HAND] = { set = "Turning Tide" },
        [EQUIP_SLOT_HEAD] = { set = "Nazaray" },
        [EQUIP_SLOT_LEGS] = { set = "Xivkyn Motif" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Puncturing Remedy" },
        [EQUIP_SLOT_NECK] = { set = "Powerful Assault" },
        [EQUIP_SLOT_OFF_HAND] = { set = "Ultimate: Aggressive Warhorn" },
        [EQUIP_SLOT_RING1] = { set = "Powerful Assault" },
        [EQUIP_SLOT_RING2] = { set = "Powerful Assault" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Nazaray" },
        [EQUIP_SLOT_WAIST] = { set = "Turning Tide" },
    },
}

SmartGear.PreBuilds["magdd_group_pet_sorcerer_heavy_attack_build_summoner"] = {
    name = "Pet Sorcerer Heavy Attack Build [Summoner]",
    role = "MagDD",
    context = "group",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Crushing Wall" },
        [EQUIP_SLOT_CHEST] = { set = "Necropotence" },
        [EQUIP_SLOT_HAND] = { set = "Necropotence" },
        [EQUIP_SLOT_HEAD] = { set = "Maw of the Infernal" },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Mother’s Sorrow" },
        [EQUIP_SLOT_NECK] = { set = "Mother’s Sorrow" },
        [EQUIP_SLOT_RING1] = { set = "Mother’s Sorrow" },
        [EQUIP_SLOT_RING2] = { set = "Mother’s Sorrow" },
        [EQUIP_SLOT_SHOULDERS] = { set = "Maw of the Infernal" },
        [EQUIP_SLOT_WAIST] = { set = "Necropotence" },
    },
}
