----------------------------------------------------------------------
-- SmartGear — Pre-Built Target Builds Database
-- Contains curated builds for each role/context.
-- Will be auto-generated by updater in the future.
----------------------------------------------------------------------
SmartGear = SmartGear or {}
SmartGear.PreBuilds = {}

----------------------------------------------------------------------
-- MagDD Trial: Ansuul's + Bahsei's + Slimecraw
-- Source: Alcast / Skinnycheeks meta (2025-2026)
----------------------------------------------------------------------
SmartGear.PreBuilds["magdd_trial_ansuul_bahsei"] = {
    name = "MagDD Trial (Ansuul + Bahsei)",
    nameRu = "МагДД Триал (Ансуул + Бахсей)",
    role = "MagDD",
    context = "trial",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_HEAD]      = { set = "Slimecraw",           trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw",           trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_MEDIUM },
        [EQUIP_SLOT_CHEST]     = { set = "Ansuul's Torment",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_WAIST]     = { set = "Ansuul's Torment",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_LEGS]      = { set = "Ansuul's Torment",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_FEET]      = { set = "Ansuul's Torment",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_HAND]      = { set = "Ansuul's Torment",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_NECK]      = { set = "Bahsei's Mania",      trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_RING1]     = { set = "Bahsei's Mania",      trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_RING2]     = { set = "Bahsei's Mania",      trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Bahsei's Mania",      trait = ITEM_TRAIT_TYPE_WEAPON_NIRNHONED },
        [EQUIP_SLOT_OFF_HAND]  = { set = "Bahsei's Mania",      trait = ITEM_TRAIT_TYPE_WEAPON_PRECISE },
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Perfected Crushing Wall", trait = ITEM_TRAIT_TYPE_WEAPON_INFUSED },
        [EQUIP_SLOT_BACKUP_OFF]  = nil,  -- 2H backbar
    },
}

----------------------------------------------------------------------
-- MagDD Solo: Briarheart + Spriggan's + Slimecraw + Pale Order
-- Source: Hack The Minotaur solo builds
----------------------------------------------------------------------
SmartGear.PreBuilds["magdd_solo_briar_spriggan"] = {
    name = "MagDD Solo (Briarheart + Spriggan)",
    nameRu = "МагДД Соло (Шиповник + Спригган)",
    role = "MagDD",
    context = "solo",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_HEAD]      = { set = "Slimecraw",           trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_SHOULDERS] = { set = "Slimecraw",           trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_MEDIUM },
        [EQUIP_SLOT_CHEST]     = { set = "Briarheart",          trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_WAIST]     = { set = "Briarheart",          trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_LEGS]      = { set = "Briarheart",          trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_FEET]      = { set = "Briarheart",          trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_HAND]      = { set = "Briarheart",          trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_NECK]      = { set = "Spriggan's Thorns",   trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_RING1]     = { set = "Ring of the Pale Order", trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_RING2]     = { set = "Spriggan's Thorns",   trait = ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Spriggan's Thorns",   trait = ITEM_TRAIT_TYPE_WEAPON_NIRNHONED },
        [EQUIP_SLOT_OFF_HAND]  = { set = "Spriggan's Thorns",   trait = ITEM_TRAIT_TYPE_WEAPON_PRECISE },
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Spriggan's Thorns", trait = ITEM_TRAIT_TYPE_WEAPON_INFUSED },
        [EQUIP_SLOT_BACKUP_OFF]  = nil,  -- 2H backbar
    },
}

----------------------------------------------------------------------
-- Tank Trial: Turning Tide + Saxhleel + Nazaray
-- Source: The Tank Club
----------------------------------------------------------------------
SmartGear.PreBuilds["tank_trial_tide_saxhleel"] = {
    name = "Tank Trial (Turning Tide + Saxhleel)",
    nameRu = "Танк Триал (Волна + Саксхлил)",
    role = "Tank",
    context = "trial",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_HEAD]      = { set = "Nazaray",             trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_SHOULDERS] = { set = "Nazaray",             trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_CHEST]     = { set = "Turning Tide",        trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_WAIST]     = { set = "Turning Tide",        trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_LEGS]      = { set = "Turning Tide",        trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_FEET]      = { set = "Turning Tide",        trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_HAND]      = { set = "Turning Tide",        trait = ITEM_TRAIT_TYPE_ARMOR_STURDY,    weight = ARMORTYPE_HEAVY },
        [EQUIP_SLOT_NECK]      = { set = "Saxhleel Champion",   trait = ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE },
        [EQUIP_SLOT_RING1]     = { set = "Saxhleel Champion",   trait = ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE },
        [EQUIP_SLOT_RING2]     = { set = "Saxhleel Champion",   trait = ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Saxhleel Champion",   trait = ITEM_TRAIT_TYPE_WEAPON_INFUSED },
        [EQUIP_SLOT_OFF_HAND]  = { set = "Saxhleel Champion",   trait = ITEM_TRAIT_TYPE_WEAPON_STURDY },
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Turning Tide",      trait = ITEM_TRAIT_TYPE_WEAPON_INFUSED },
        [EQUIP_SLOT_BACKUP_OFF]  = nil,
    },
}

----------------------------------------------------------------------
-- Healer Trial: Olorime + SPC + Symphony of Blades
-- Source: Alcast healer builds
----------------------------------------------------------------------
SmartGear.PreBuilds["healer_trial_olorime_spc"] = {
    name = "Healer Trial (Olorime + SPC)",
    nameRu = "Хилер Триал (Олориме + SPC)",
    role = "Healer",
    context = "trial",
    source = "alcast",
    slots = {
        [EQUIP_SLOT_HEAD]      = { set = "Symphony of Blades",  trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_SHOULDERS] = { set = "Symphony of Blades",  trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_CHEST]     = { set = "Spell Power Cure",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_WAIST]     = { set = "Spell Power Cure",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_LEGS]      = { set = "Spell Power Cure",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_FEET]      = { set = "Spell Power Cure",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_HAND]      = { set = "Spell Power Cure",    trait = ITEM_TRAIT_TYPE_ARMOR_DIVINES,   weight = ARMORTYPE_LIGHT },
        [EQUIP_SLOT_NECK]      = { set = "Olorime",             trait = ITEM_TRAIT_TYPE_JEWELRY_ARCANE },
        [EQUIP_SLOT_RING1]     = { set = "Olorime",             trait = ITEM_TRAIT_TYPE_JEWELRY_ARCANE },
        [EQUIP_SLOT_RING2]     = { set = "Olorime",             trait = ITEM_TRAIT_TYPE_JEWELRY_ARCANE },
        [EQUIP_SLOT_MAIN_HAND] = { set = "Olorime",             trait = ITEM_TRAIT_TYPE_WEAPON_POWERED },
        [EQUIP_SLOT_OFF_HAND]  = nil,
        [EQUIP_SLOT_BACKUP_MAIN] = { set = "Olorime",           trait = ITEM_TRAIT_TYPE_WEAPON_INFUSED },
        [EQUIP_SLOT_BACKUP_OFF]  = nil,
    },
}
