"""
SmartGear Lua Generator — produces MetaData.lua from merged set data
"""
import datetime


def _escape_lua_string(s):
    """Escape a string for Lua."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def _format_roles(roles):
    """Format roles list as Lua table."""
    parts = [f'"{r}"' for r in roles]
    return "{ " + ", ".join(parts) + " }"


def generate_metadata_lua(sets, output_path):
    """Generate MetaData.lua from merged set data.

    Args:
        sets: list of set dicts from merger
        output_path: path to write MetaData.lua
    """
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    total = len(sets)

    lines = []
    lines.append("----------------------------------------------------------------------")
    lines.append("-- SmartGear — Meta Set Database")
    lines.append(f"-- AUTO-GENERATED by SmartGear Updater on {now}")
    lines.append(f"-- Total sets: {total}")
    lines.append("-- Do not edit manually — changes will be overwritten!")
    lines.append("-- Use overrides.json for manual adjustments.")
    lines.append("----------------------------------------------------------------------")
    lines.append("SmartGear = SmartGear or {}")
    lines.append("")

    # RoleConfig (static, not generated)
    lines.append("----------------------------------------------------------------------")
    lines.append("-- Role definitions & optimal traits/weights")
    lines.append("----------------------------------------------------------------------")
    lines.append("SmartGear.RoleConfig = {")
    lines.append("    MagDD = {")
    lines.append("        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },")
    lines.append("        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },")
    lines.append("        optimalWeights = { [ARMORTYPE_LIGHT] = true },")
    lines.append("        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = true },")
    lines.append("        optimalWeaponTraits = {")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_PRECISE] = true,")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,")
    lines.append("        },")
    lines.append('        description = "Magicka Damage Dealer",')
    lines.append("    },")
    lines.append("    StamDD = {")
    lines.append("        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },")
    lines.append("        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },")
    lines.append("        optimalWeights = { [ARMORTYPE_MEDIUM] = true },")
    lines.append("        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY] = true },")
    lines.append("        optimalWeaponTraits = {")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_PRECISE] = true,")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,")
    lines.append("        },")
    lines.append('        description = "Stamina Damage Dealer",')
    lines.append("    },")
    lines.append("    Tank = {")
    lines.append("        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_STURDY] = true },")
    lines.append("        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },")
    lines.append("        optimalWeights = { [ARMORTYPE_HEAVY] = true },")
    lines.append("        optimalJewelryTrait = {")
    lines.append("            [ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE] = true,")
    lines.append("            [ITEM_TRAIT_TYPE_JEWELRY_TRIUNE] = true,")
    lines.append("        },")
    lines.append("        optimalWeaponTraits = {")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_DECISIVE] = true,")
    lines.append("        },")
    lines.append('        description = "Tank",')
    lines.append("    },")
    lines.append("    Healer = {")
    lines.append("        optimalTraits = { [ITEM_TRAIT_TYPE_ARMOR_DIVINES] = true },")
    lines.append("        pvpTraits     = { [ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE] = true },")
    lines.append("        optimalWeights = { [ARMORTYPE_LIGHT] = true },")
    lines.append("        optimalJewelryTrait = { [ITEM_TRAIT_TYPE_JEWELRY_ARCANE] = true },")
    lines.append("        optimalWeaponTraits = {")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_POWERED] = true,")
    lines.append("            [ITEM_TRAIT_TYPE_WEAPON_INFUSED] = true,")
    lines.append("        },")
    lines.append('        description = "Healer",')
    lines.append("    },")
    lines.append("}")
    lines.append("")

    # TraitNames (static)
    lines.append("----------------------------------------------------------------------")
    lines.append("-- Trait display names")
    lines.append("----------------------------------------------------------------------")
    lines.append("SmartGear.TraitNames = {")
    trait_map = [
        ("ITEM_TRAIT_TYPE_ARMOR_DIVINES", "Divines"),
        ("ITEM_TRAIT_TYPE_ARMOR_IMPENETRABLE", "Impenetrable"),
        ("ITEM_TRAIT_TYPE_ARMOR_INFUSED", "Infused"),
        ("ITEM_TRAIT_TYPE_ARMOR_REINFORCED", "Reinforced"),
        ("ITEM_TRAIT_TYPE_ARMOR_STURDY", "Sturdy"),
        ("ITEM_TRAIT_TYPE_ARMOR_TRAINING", "Training"),
        ("ITEM_TRAIT_TYPE_ARMOR_WELL_FITTED", "Well-Fitted"),
        ("ITEM_TRAIT_TYPE_ARMOR_NIRNHONED", "Nirnhoned"),
        ("ITEM_TRAIT_TYPE_WEAPON_PRECISE", "Precise"),
        ("ITEM_TRAIT_TYPE_WEAPON_INFUSED", "Infused"),
        ("ITEM_TRAIT_TYPE_WEAPON_SHARPENED", "Sharpened"),
        ("ITEM_TRAIT_TYPE_WEAPON_CHARGED", "Charged"),
        ("ITEM_TRAIT_TYPE_WEAPON_POWERED", "Powered"),
        ("ITEM_TRAIT_TYPE_WEAPON_DECISIVE", "Decisive"),
        ("ITEM_TRAIT_TYPE_WEAPON_NIRNHONED", "Nirnhoned"),
        ("ITEM_TRAIT_TYPE_WEAPON_TRAINING", "Training"),
        ("ITEM_TRAIT_TYPE_JEWELRY_ARCANE", "Arcane"),
        ("ITEM_TRAIT_TYPE_JEWELRY_BLOODTHIRSTY", "Bloodthirsty"),
        ("ITEM_TRAIT_TYPE_JEWELRY_HARMONY", "Harmony"),
        ("ITEM_TRAIT_TYPE_JEWELRY_INFUSED", "Infused"),
        ("ITEM_TRAIT_TYPE_JEWELRY_PROTECTIVE", "Protective"),
        ("ITEM_TRAIT_TYPE_JEWELRY_ROBUST", "Robust"),
        ("ITEM_TRAIT_TYPE_JEWELRY_SWIFT", "Swift"),
        ("ITEM_TRAIT_TYPE_JEWELRY_TRIUNE", "Triune"),
    ]
    for const, name in trait_map:
        lines.append(f'    [{const}] = "{name}",')
    lines.append("}")
    lines.append("")

    # MetaSets (generated!)
    lines.append("----------------------------------------------------------------------")
    lines.append("-- Meta Sets Database (auto-generated)")
    lines.append("----------------------------------------------------------------------")
    lines.append("SmartGear.MetaSets = {")
    lines.append("")

    # Group by category for readability
    categories_order = [
        "Trial", "Dungeon", "Arena", "Crafted", "Overland",
        "Monster Set", "Mythic", "PvP", "Unknown",
    ]

    sets_by_cat = {}
    for s in sets:
        cat = s.get("source", "Unknown")
        # Use a more meaningful grouping
        if s["is_mythic"]:
            cat = "Mythic"
        elif s["is_monster"]:
            cat = "Monster Set"
        elif s["is_pvp"]:
            cat = "PvP"
        sets_by_cat.setdefault(cat, []).append(s)

    for cat in categories_order:
        cat_sets = sets_by_cat.pop(cat, [])
        if not cat_sets:
            continue

        lines.append(f"    -- {cat.upper()} SETS")
        for s in cat_sets:
            name = _escape_lua_string(s["name"])
            roles = _format_roles(s["roles"])
            tier = s["tier"]
            source = _escape_lua_string(s.get("source", "Unknown"))
            notes = _escape_lua_string(s.get("notes", ""))

            lines.append(f'    ["{name}"] = {{')
            lines.append(f'        roles = {roles},')
            lines.append(f'        tier = "{tier}",')
            lines.append(f'        rating = {s.get("rating", 50)},')
            lines.append(f'        source = "{source}",')
            lines.append(f'        notes = "{notes}",')
            if s.get("is_monster"):
                lines.append(f'        isMonsterSet = true,')
            if s.get("is_mythic"):
                lines.append(f'        isMythic = true,')
            if s.get("is_pvp"):
                lines.append(f'        pvpOnly = true,')
            lines.append(f'    }},')

        lines.append("")

    # Remaining categories
    for cat, cat_sets in sets_by_cat.items():
        if not cat_sets:
            continue
        lines.append(f"    -- {cat.upper()} SETS")
        for s in cat_sets:
            name = _escape_lua_string(s["name"])
            roles = _format_roles(s["roles"])
            tier = s["tier"]
            source = _escape_lua_string(s.get("source", "Unknown"))
            notes = _escape_lua_string(s.get("notes", ""))

            lines.append(f'    ["{name}"] = {{')
            lines.append(f'        roles = {roles},')
            lines.append(f'        tier = "{tier}",')
            lines.append(f'        rating = {s.get("rating", 50)},')
            lines.append(f'        source = "{source}",')
            lines.append(f'        notes = "{notes}",')
            if s.get("is_monster"):
                lines.append(f'        isMonsterSet = true,')
            if s.get("is_mythic"):
                lines.append(f'        isMythic = true,')
            if s.get("is_pvp"):
                lines.append(f'        pvpOnly = true,')
            lines.append(f'    }},')
        lines.append("")

    lines.append("}")
    lines.append("")

    # StatCaps (static)
    lines.append("----------------------------------------------------------------------")
    lines.append("-- Stat caps reference")
    lines.append("----------------------------------------------------------------------")
    lines.append("SmartGear.StatCaps = {")
    lines.append("    physicalPenetration = 18200,")
    lines.append("    spellPenetration    = 18200,")
    lines.append("    criticalChance      = 125,")
    lines.append("    criticalDamage      = 125,")
    lines.append("    weaponDamage        = 0,")
    lines.append("    spellDamage         = 0,")
    lines.append("}")
    lines.append("")

    # Write
    content = "\n".join(lines)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"[lua-gen] Generated MetaData.lua with {total} sets -> {output_path}")
    return output_path
